### ISSUE TITLE
Docker config location

### ISSUE THREAD

**Issue by redstorm1** [toxuin/mdns-tunneller#7]
docker run -v your_config_file.yml:/app/config/local.yml -p 42069:42069 toxuin/mdns-tunneller

I tried initially to use the docker image but i could not get it to pickup and use my local.yml, could you provide some more detail on setting up the docker config file?

**Comment by toxuin** [comment]
You'd either need to provide a full path to your config file or use `$PWD` as the pointer to current directory.

For example, for me config file lives in `/home/toxuin/mdns-tunneller/config.yml`.
I can either start the container with
`docker run -v /home/toxuin/mdns-tunneller/config.yml:/app/config/local.yml ...`
or 
`cd /home/toxuin/mdns-tunneller`
`docker run -v $PWD/config.yml:/app/config/local.yml ...`

**Comment by redstorm1** [comment]
perfect thanks, for the life of me i couldn't get the path right initially.

its working well enough that the remote sensors can find the server and report so making the config more robust to continue on reboot.
