### ISSUE TITLE
Tunnel through wireguard

### ISSUE THREAD

**Issue by Goeks1** [toxuin/mdns-tunneller#8]
Hi,
I have a Homeserver running. On this runs a IoBroker Docker container with the adapter yahka (yet another Homekit adapter).
This Homeserver(10.0.5.6)  is connected to my main server (10.0.5.1) via VPN interface wg0. Furthermore my Iphone (10.0.5.2) is also in the same VPN network. 
The mdns-tunnler is pulled from git and runs with default configuration inside the IoBroker Container in the server mode. Furthermore the port 42069 is also bind to the container.

In theory, if I have understood this project correctly, I should now be able to reach my Homekit devices with my Iphone via the VPN tunnel. Unfortunately the devices are not reachable.

Homeserver Logs:
```
$ npm run start:prod

> mdns-tunneller@1.0.0 start:prod /root/mdns-tunneller
> node .build/index.js

Started server on 0.0.0.0:42069
Client connected: ::ffff:10.0.5.1:39560
```
Main server Logs:
```
$ docker run -v /home/docker/mdns-tunneller/config/local.yml:/app/config/local.yml -p 42069:42069 toxuin/mdns-tunneller

> mdns-tunneller@1.0.0 start:prod
> node .build/index.js

Connecting to http://10.0.5.6:42069...
Connected to the remote: http://10.0.5.6:42069
```

Main Server Configuration
```
port: 42069
enableIpv6: true

# THIS IS WHERE SERVER WILL LISTEN ON HTTP CONNECTIONS
interface:
  - 0.0.0.0

# UNCOMMENT TO LISTEN FOR MDNS PACKETS ONLY ON SPECIFIC INTERFACES:
#mdnsInterfaces:
  - wg0

sendersBlacklist:
  - '127.0.0.1'

serviceWhitelist:
  - '_homekit._tcp.local'
  - '_hap._tcp.local'
# UNCOMMENT THIS TO ADD SUPPORT FOR CHROMECAST
#  - '_googlecast._tcp.local'

# UNCOMMENT THIS TO START AS A CLIENT:
remote: 10.0.5.6
# or
# remote: https://10.0.5.6
```

**Comment by toxuin** [comment]
Are you connecting to yourself here? 🤔 As in, is the server also a client?.. That's not how it's supposed to work.

I have setup pretty similar to this one. You would need a device like a raspberry pi in the same network as where the iPhones and AppleTVs are. On it, you run the mdns-tunneller in client mode and on your server you run the server counterpart.
